version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    assignees:
      - frequency403
    schedule:
      interval: "monthly"

  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "develop"
    assignees:
      - frequency403
    schedule:
      interval: "monthly"

    open-pull-requests-limit: 10

    groups:
      nuget-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

    labels:
      - "dependencies"
      - "nuget"

    commit-message:
      prefix: "chore(deps)"