name: Create release tag on merge

on:
  pull_request:
    types: [ closed ]
    branches:
      - main
permissions:
  contents: write

jobs:
  create-and-push-tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Create & push tag
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: 0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5

      - uses: ./.github/actions/get-version
        id: version
        with:
          file-name: Directory.Build.props
          
      - name: Create tag
        uses: tvdias/github-tagger@v0.0.2
        with: 
          commit-sha: ${{ github.event.pull_request.merge_commit_sha }}
          repo-token: ${{ github.token }}
          tag: ${{ steps.version.outputs.tag }}